name: Default

on:
  push:
    branches-ignore:
      - main

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v3

      - run: npm install
      - run: npm run all

      - uses: ./
        id: test-1
        with:
          version: wrong
          lenient: false
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.test-1.outcome }}" ]]'
      - run: '[[ "success" == "${{ steps.test-1.conclusion }}" ]]'

      - uses: ./
        id: test-2
        with:
          version: wrong
          lenient: 'false'
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.test-2.outcome }}" ]]'
      - run: '[[ "success" == "${{ steps.test-2.conclusion }}" ]]'

      - uses: ./
        id: test-3
        with:
          version: wrong
      - run: '[[ "" == "${{ steps.test-3.outputs.release }}" ]]'
      - run: '[[ "" == "${{ steps.test-3.outputs.major }}" ]]'
      - run: '[[ "" == "${{ steps.test-3.outputs.minor }}" ]]'
      - run: '[[ "" == "${{ steps.test-3.outputs.patch }}" ]]'
      - run: '[[ "" == "${{ steps.test-3.outputs.any_other_property }}" ]]'

      - uses: ./
        id: test-4
        with:
          version: wrong
          lenient: true
      - run: '[[ "" == "${{ steps.test-4.outputs.release }}" ]]'
      - run: '[[ "" == "${{ steps.test-4.outputs.major }}" ]]'
      - run: '[[ "" == "${{ steps.test-4.outputs.minor }}" ]]'
      - run: '[[ "" == "${{ steps.test-4.outputs.patch }}" ]]'
      - run: '[[ "" == "${{ steps.test-4.outputs.any_other_property }}" ]]'

      - uses: ./
        id: test-5
        with:
          version: 1.2.3-alpha.gamma+4.5.6
      - run: '[[ "1.2.3"       == "${{ steps.test-5.outputs.release }}" ]]'
      - run: '[[ "1"           == "${{ steps.test-5.outputs.major }}" ]]'
      - run: '[[ "2"           == "${{ steps.test-5.outputs.minor }}" ]]'
      - run: '[[ "3"           == "${{ steps.test-5.outputs.patch }}" ]]'
      - run: '[[ "alpha.gamma" == "${{ steps.test-5.outputs.prerelease }}" ]]'
      - run: '[[ "2"           == "${{ steps.test-5.outputs.prerelease-parts }}" ]]'
      - run: '[[ "alpha"       == "${{ steps.test-5.outputs.prerelease-0 }}" ]]'
      - run: '[[ "gamma"       == "${{ steps.test-5.outputs.prerelease-1 }}" ]]'
      - run: '[[ "4.5.6"       == "${{ steps.test-5.outputs.build }}" ]]'
      - run: '[[ "3"           == "${{ steps.test-5.outputs.build-parts }}" ]]'
      - run: '[[ "4"           == "${{ steps.test-5.outputs.build-0 }}" ]]'
      - run: '[[ "5"           == "${{ steps.test-5.outputs.build-1 }}" ]]'
      - run: '[[ "6"           == "${{ steps.test-5.outputs.build-2 }}" ]]'

      - uses: ./
        id: test-6
        with:
          version: 1.0.0
          compare-to: 2.0.0
      - run: '[[ "<" == "${{ steps.test-6.outputs.comparison-result }}" ]]'

      - uses: ./
        id: test-7
        with:
          version: 1.2.3
          satisfies: 1.x
      - run: '[[ "true" == "${{ steps.test-7.outputs.satisfies }}" ]]'

      - uses: ./
        id: test-8
        with:
          version: 1.2.3
      - run: '[[ "2.0.0"   == "${{ steps.test-8.outputs.inc-major }}" ]]'
      - run: '[[ "2.0.0-0" == "${{ steps.test-8.outputs.inc-premajor }}" ]]'
      - run: '[[ "1.3.0"   == "${{ steps.test-8.outputs.inc-minor }}" ]]'
      - run: '[[ "1.3.0-0" == "${{ steps.test-8.outputs.inc-preminor }}" ]]'
      - run: '[[ "1.2.4"   == "${{ steps.test-8.outputs.inc-patch }}" ]]'
      - run: '[[ "1.2.4-0" == "${{ steps.test-8.outputs.inc-prepatch }}" ]]'
      - run: '[[ "1.2.4-0" == "${{ steps.test-8.outputs.inc-prerelease }}" ]]'

  actions-typing:
    name: Validate actions typing
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v3
      - uses: krzema12/github-actions-typing@v1
